config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "posts#index"
    devise_for :users
    resources :users, only: :show
    get "/posts/:context", to: "posts#index", as: :posts_index
    resources :categories, only: [:index, :show] do
      resources :topics, only: [:index, :show] do
        resource :posts, only: [:index, :show]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banning_category.rb
class BanningCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_managements, dependent: :destroy
  has_many :banning_categories, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :posts, through: :topics

  scope :most_category, ( lambda do | current_user|
    pushlished.joins(:votes).select("topic.*, SUM(votes.status) AS total_vote")
      .group(:id).order("total_vote DESC") if banning?(current_user)
  end)

  scope :largest_category, ->{ joins(:topics, topics: :posts).select("categories.*, COUNT(*) AS total_posts").group(:id).having("total_posts = MAX(total_posts)").first }

  def banning? current_user
    banning_categories.where(user: current_user)
  end
end

app/models/category_management.rb
class CategoryManagement < ApplicationRecord
  belongs_to :moderator, class_name: "User"
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { draft: 1, pushlish: 2 }

  belongs_to :topic

  has_many :votes, as: :ownerable, dependent: :destroy

  scope :pushlished, ->{ joins(:votes).where(status: :pushlish).includes(:topic, topic: [:user, :category]) }
  scope :cal_vote, ->{ pushlished.select("posts.*, SUM(votes.status) AS total_vote").group(:id) }
  scope :newest, ->{ cal_vote.order(created_at: :desc) }

  delegate :category, to: :topic
  delegate :user, to: :topic

  class<<self
    def _on context
      case context
      when nil
        newest
      when "newest"
        newest
      when "most_upvote"
        cal_vote.order("total_vote DESC")
      when "on_largest_category"
        Category.largest_category.posts.cal_vote
      else
        newest
      end
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  enum status: { pending: 1, active: 2, blocked: 3 }

  belongs_to :user
  belongs_to :category

  has_many :posts, dependent: :destroy
  has_many :votes, as: :ownerable, dependent: :destroy

  scope :most_upvote, -> { joins(:votes).select("topics.*, SUM(votes.status) AS total_vote_topic").group(:id).order("total_vote_topic DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  enum sex: { male: 0, female: 1 }
  enum role: { admin: 1, moderator: 2, normal: 3 }

  devise :database_authenticatable, :registerable, :recoverable, :rememberable

  has_many :votes
  has_many :banning_categories, dependent: :destroy
  has_many :category_managements, ->{ where(role: :moderator) }
  has_many :topics, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  enum status: { down_vote: -1, none: 0, up_vote: 1 }, _suffix: true

  belongs_to :user
  belongs_to :ownerable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :all_category

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def all_category
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category

  def show
    @posts = Post.where(topic: category.topics).cal_vote.page(params[:page])
  end

  attr_reader :category

  def find_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post._on(params[:context]).page(params[:page])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
 def index
  
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    return if user
  end

  attr_reader :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_side_bar.html.erb
<!-- Left sidebar -->
<aside class="col-md-3">
  <div class="sidebar-box">
      <div class="list-group list-group-root">
          <% categories.each do |category| %>
            <%= link_to category.title, category_path(id: category.id), class: "category list-group-item" %>
          <% end %>
      </div>
  </div>
</aside>

app/views/categories/show.html.erb
<main class="container">
	<div class="row">
		<%= render "side_bar", categories: @categories %>
		<div class="col-md-6">
			<%= render "posts/post_form", posts: @posts %>
      <%= paginate @posts, theme: "twitter-bootstrap-3" %>
		</div>
		<%= render "shareds/right_side_bar" %>
	</div>
</main>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container footer-container">
    <footer class="footer">
        <div class="footer-lists">
            <div class="row">
                <div class="col-sm">
                    <ul>
                        <li><h4>Proin accumsan</h4></li>
                        <li><a href="#">Rutrum nulla a ultrices</a></li>
                        <li><a href="#">Blandit elementum</a></li>
                        <li><a href="#">Proin placerat accumsan</a></li>
                        <li><a href="#">Morbi hendrerit libero </a></li>
                        <li><a href="#">Curabitur sit amet tellus</a></li>
                    </ul>
                </div>
                <div class="col-sm">
                    <ul>
                        <li><h4>Condimentum</h4></li>
                        <li><a href="#">Curabitur sit amet tellus</a></li>
                        <li><a href="#">Morbi hendrerit libero </a></li>
                        <li><a href="#">Proin placerat accumsan</a></li>
                        <li><a href="#">Rutrum nulla a ultrices</a></li>
                        <li><a href="#">Cras dictum</a></li>
                    </ul>
                </div>
                <div class="col-sm">
                    <ul>
                        <li><h4>Suspendisse</h4></li>
                        <li><a href="#">Morbi hendrerit libero </a></li>
                        <li><a href="#">Proin placerat accumsan</a></li>
                        <li><a href="#">Rutrum nulla a ultrices</a></li>
                        <li><a href="#">Curabitur sit amet tellus</a></li>
                        <li><a href="#">Donec in ligula nisl.</a></li>
                    </ul>
                </div>
                <div class="col-sm">
                    <h4>Suspendisse</h4>
                    <p>Integer mattis blandit turpis, quis rutrum est. Maecenas quis arcu vel felis lobortis iaculis fringilla at ligula. Nunc dignissim porttitor dolor eget porta.</p>

                    <p class="social-icons">
                        <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                        <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                        <a href="#"><i class="fa fa-youtube fa-2x"></i></a>
                        <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                    </p>
                </div>
            </div>
        </div>

        <div class="footer-bottom">
                <p class="text-center">Built by
                  <a href="https://www.google.com.vn/search?q=KhongBietDatTenGiChoNoHayVaYNghia&oq=KhongBietDatTenGiChoNoHayVaYNghia&aqs=chrome..69i57j69i60l3j69i59l2.18467j0j7&sourceid=chrome&ie=UTF-8">
                    KhongBietDatTenGiChoNoHayVaYNghia Team
                  </a>.
                </p>
                <p class="text-center"><a href="#">Back to top</a></p>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="user_info">
      <%= link_to "Info", "#" %>
      |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
    <div class="header-wrap d-none d-md-block">
      <div class="row">
        <header class="col-6 text-left">
          <h1><span>PINK</span>~~~~~~~~~~~~~~~forum</h1>
        </header>
      </div>
    </div>
    </div>

    <div class="container navbar-container">
      <nav class="navbar navbar-expand-md navbar-light">
        <a class="navbar-brand d-md-none d-lg-none d-xl-none" href="#"><span>PINK</span>~~~~~~~~~~~~~~~forum</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mainNavbar">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown active">
              <a class="nav-link " href="#">Trang chủ</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link " href="#">Topic của tôi</a>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link " href="#">Tạo bài viết mới</a>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link " href="#">Bài viết được gắn</a>
            </li>
          </ul>

          <form class="form-inline header-search-form my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" size="10"  placeholder="Search" aria-label="Search">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PINK forum</title>
    <%= csrf_meta_tags %>
    <!-- <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script>
      I18n.locale = '<%= I18n.locale %>';
    </script>
  </head>

  <body>
    <%= render"layouts/header" %>
    <%= yield %>
    <%= render"layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/_post_form.html.erb
<% posts.each do |post| %>
  <article>
      <h2 class="article-title"><%= post.title %></h2>
      <p class="article-meta">
        <%= link_to post.category.title, category_path(id: post.category.id), rel: "category" %>
        <a> | </a>
        
        <a href="#" rel="topic"><%= post.topic.title %></a>
        <a> | </a>
        <a><%= post.total_vote %> upvote</a>
        </p>
      <p class="article-meta">Posted on <time datetime="2017-05-14"><%= post.created_at %></time> by <a href="#" rel="author">
        <% if  post.user.id == current_user.id %>
          <%= post.user.name %>
        <% else %>
          you
        <% end %>
      </a></p>

      <p><%= post.content %></p>

      <a href="#" class="btn btn-primary">Read more</a>
      <a href="#" class="btn btn-secondary">Comments</a>

  </article>
<% end %>

app/views/posts/index.html.erb
<main class="container">
	<div class="row">
		<%= render "categories/side_bar", categories: @categories %>
		<div class="col-md-6">
			<%= render "post_form", posts: @posts %>
      <%= paginate @posts, theme: "twitter-bootstrap-3" %>
		</div>
		<%= render "shareds/right_side_bar" %>
	</div>
</main>

app/views/shareds/_flash_errors.html.erb
<% flash.each do |message_type, message| %>
  <div class="autohide alert alert-<%= message_type.gsub('alert', 'warning') %>
    text-center">
    <%= message.try(:html_safe) %>
  </div>
<% end %>

app/views/shareds/_right_side_bar.html.erb
<!-- Right Sidebar -->
<aside class="col-md-3">
  <div class="sidebar-box">
    <div class="list-group list-group-root">
      <%= link_to "Các bài viết mới nhất", posts_index_path(context: "newest"), class:"list-group-item" %>
      <%= link_to "Các chuyên mục nổi bật", posts_index_path(context: "on_largest_category"), class:"list-group-item" %>
      <%= link_to "Các topic nổi bật", posts_index_path(context: "on_topic_most_upvote"), class:"list-group-item" %>
      <%= link_to "Các bài viết nổi bật", posts_index_path(context: "most_upvote"), class:"list-group-item" %>
    </div>
  </div>

  <div class="sidebar-box sidebar-box-bg">
    <h5 class="block-inline">Số người dùng online: </h5><span> 100</span>
  </div>
</aside>

app/views/static_pages/index.html.erb
<main class="container">
	<div class="row">
		<%= render "categories/side_bar", categories: @categories %>
		<div class="col-md-6">
			<%= render "posts/post_form", posts: @newest_posts %>
			<nav>
				<ul class="pagination">
					<li class="page-item">
						<a class="page-link" href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
							<span class="sr-only">Previous</span>
						</a>
					</li>
					<li class="page-item"><a class="page-link" href="#">1</a></li>
					<li class="page-item active"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item">
						<a class="page-link" href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
		<%= render "shareds/right_side_bar" %>
	</div>
</main>

app/views/topics/index.html.erb
<main class="container">
    <div class="row">
        <%= render "categories/side_bar", categories: @categories %>
        <div class="col-md-6">
            <% @topics_on_category.each do |topic| %>
              <article>
                  <h2 class="article-title"><%= topic.title %></h2>
                  <p class="article-meta">Posted on <time datetime="2017-05-14"><%= post.created_at %></time> by <a href="#" rel="author"><!-- Athor --></a></p>

                  <p><%= topic.content %></p>

                  <ul>
                      <li>Firefox</li>
                      <li>IE / Edge</li>
                      <li>Chrome</li>
                      <li>Safari</li>
                      <li>iOS / Android</li>
                  </ul>
                  <a href="#" class="btn btn-primary">Read more</a>
                  <a href="#" class="btn btn-secondary">Comments</a>
              </article>
            <% end %>

            <!-- Example pagination Bootstrap component -->
            <nav>
                <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                </ul>
            </nav>
        </div>
        <%= render "shareds/right_side_bar" %>
    </div>
</main>

app/views/users/show.html.erb
dsad